django_app/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("plast", views.plast, name="plast"),
    path("msgs/<int:page>", views.msgs, name="msgs"),
    path("usr", views.usr, name="usr"),
    path("usr/<int:usr_id>", views.usr, name="usr"),
    path("post", views.post, name="post"),
    path("good/<int:good_id>", views.good, name="good"),
]

django_app/django_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('sns/', include('sns.urls')),
    path('api/', include('api.urls')),
]

django_app/hello/urls.py
from django.urls import path
from .views import FriendList, FriendDetail
from . import views
# from .views import HelloView

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:num>', views.index, name='index'),
    path('create',views.create,name='create'),
    path('edit/<int:num>',views.edit,name='edit'),
    path('delete/<int:num>',views.delete,name='delete'),
    path('list', FriendList.as_view()),
    path('detail/<int:pk>', FriendDetail.as_view()),
    path('find', views.findSql, name='find'),
    path('check', views.check, name='check'),
    path('message/', views.message, name='message'),
    path('message/<int:page>', views.message, name='message'),
    # path('<int:id>/<nickname>/', views.index, name='index'),
    # path('form', views.form, name='form'),
    # path('next', views.next, name='next'),
    # path('test', views.test, name='test'),
    # path('',HelloView.as_view(),name='index'),
]

django_app/hello/models.py
import re
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, MinLengthValidator, URLValidator, RegexValidator, ValidationError

def number_only(value):
    if (re.match(r'^[0-9]*$', value) == None):
        raise ValidationError(
            '%(value)s is not Number!',
            params={'value': value},
        )

# Create your models here.
# ユーザー管理
class Friend(models.Model):
    name = models.CharField(max_length=100)
    mail = models.EmailField(max_length=200)
    gender = models.BooleanField()
    age = models.IntegerField()
    birthday = models.DateField()


# メッセージ管理
class Message(models.Model):
    friend = models.ForeignKey(Friend, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=300)
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('pub_date',)

# class Friend(models.Model):
#     # name = models.CharField(max_length=100, validators=[MinLengthValidator(10)])
#     name = models.CharField(max_length=100, validators=[RegexValidator(r'^[a-z]*$')])
#     # name = models.CharField(max_length=100, validators=[URLValidator()])
#     mail = models.EmailField(max_length=200, validators=[MinLengthValidator(10)])
#     gender = models.BooleanField()
#     age = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(150)])
#     birthday = models.DateField()

    # def __str__(self):
    #     return '<Friend:id=' + str(self.id) + ',' + self.name + '(' + str(self.age) + ')>'

django_app/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from .models import Friend, Message
from .forms import SearchForm
from .forms import FriendForm, MessageForm
from .forms import FindForm
from .forms import CheckForm
from django.shortcuts import redirect
from django.db.models import Q
from django.db.models import Count
from django.db.models import Sum
from django.db.models import Avg
from django.db.models import Min
from django.db.models import Max
from django.core.paginator import Paginator
# from .forms import SessionForm
# from .forms import HelloForm


## ミドルウェア
def sample_middleware(get_response):

    def middleware(request):
        counter = request.session.get('counter',0)
        request.session['counter'] = counter + 1
        response = get_response(request)
        print("count:" + str(counter))
        return response
    return middleware


def index(request, num=1):
    data = Friend.objects.all()
    page = Paginator(data, 3)
    # re1 = Friend.objects.aggregate(Count('age'))
    # re2 = Friend.objects.aggregate(Sum('age'))
    # re3 = Friend.objects.aggregate(Avg('age'))
    # re4 = Friend.objects.aggregate(Min('age'))
    # re5 = Friend.objects.aggregate(Max('age'))

    # msg = "count:" + str(re1['age__count']) + "<br>Sum:" + str(re2['age__sum']) + "<br>Avg:" + str(re3['age__avg']) + "<br>Min:" + str(re4['age__min']) + "<br>Max:" + str(re5['age__max'])

    params = {
        'title':'Hello',
        'message':'all friends',
        # 'form':SearchForm(),
        'data':page.get_page(num),
        # 'msg':msg
    }
    # if(request.method == "POST"):
    #     num = request.POST['id']
    #     try:
    #         item = Friend.objects.get(id=num)
    #         params['data'] = [item]
    #     except:
    #         pass
    #     params['form'] = SearchForm(request.POST)
    return render(request,"hello/index.html",params)


def create(request):
    if(request.method == "POST"):
        obj = Friend()
        friend = FriendForm(request.POST,instance=obj)
        friend.save()
        return redirect(to="/hello")
    params={
        "title":"Hello",
        "form":FriendForm(),
        # "form":HelloForm(),
    }
    # if(request.method=="POST"):
    #     name = request.POST['name']
    #     mail = request.POST['mail']
    #     gender = "gender" in request.POST
    #     age = request.POST['age']
    #     birthday = request.POST['birthday']
    #     friend = Friend(name=name,mail=mail,gender=gender,age=age,birthday=birthday)

    #     friend.save()
        
    #     return redirect(to="/hello")

    return render(request,"hello/create.html",params)


## edit
def edit(request, num):
    obj = Friend.objects.get(id=num)

    if(request.method == "POST"):
        friend = FriendForm(request.POST,instance=obj)
        friend.save()
        return redirect(to="/hello")

    params={
        'title':'Hello',
        'form':FriendForm(instance=obj),
        'id':num,
    }

    return render(request,"hello/edit.html",params)


## delete
def delete(request, num):
    obj = Friend.objects.get(id=num)

    if(request.method == "POST"):
        obj.delete()
        return redirect(to="/hello")

    params={
        'title':'Hello',
        'obj':obj,
        'id':num,
    }

    return render(request,"hello/delete.html",params)


# find関数
# def find(request):
#     if(request.method == 'POST'):
#         find = request.POST['find']
#         # data = Friend.objects.filter(Q(name__contains=find) | Q(mail__contains=find))
#         list = find.split() # 半角スペースで区切ってリスト化
#         # data = Friend.objects.filter(name__in=list)
#         data = Friend.objects.all()[int(list[0]):int(list[1])]
#         msg = '検索結果:'+str(data.count())
#     else:
#         msg = '検索ワード'
#         data = Friend.objects.all()
#     params = {
#         'title':'Hello',
#         'message':msg,
#         'form':FindForm(),
#         'data':data,
#     }

#     return render(request, 'hello/find.html', params)


def findSql(request):
    if(request.method == 'POST'):
        find = request.POST['find']
        sql = "select * from hello_friend"

        if (find != ''):
            sql += ' where ' + find
        data = Friend.objects.raw(sql)
        msg = sql
    else:
        msg = '検索ワード'
        data = Friend.objects.all()
    params = {
        'title':'Hello',
        'message':msg,
        'form':FindForm(),
        'data':data,
    }

    return render(request, 'hello/find.html', params)


def check(request):
    params = {
        'title':'Hello',
        'message':'check validation',
        'form':FriendForm(),
    }
    if (request.method == 'POST'):
        form = FriendForm(request.POST)
        params['form'] = form
        if (form.is_valid()):
            params['message'] = 'OK!'
        else:
            params['message'] = 'no good.'

    return render(request, 'hello/check.html', params)


def message(request, page=1):
    if (request.method == "POST"):
        obj = Message()
        form = MessageForm(request.POST, instance=obj)
        form.save()
    data = Message.objects.all().reverse()
    paginator = Paginator(data, 5)
    params = {
        'title':'Message',
        'form':MessageForm(),
        'data':paginator.get_page(page),
    }

    return render(request, "hello/message.html", params)


class FriendList(ListView):
    model = Friend


class FriendDetail(DetailView):
    model = Friend


## getリクエストの受け取り方
# Create your views here.
# def index(request):
#     if 'msg' in request.GET:
#         msg = request.GET['msg']
#         result = 'you typed:"' + msg + '".'
#     else:
#         result = 'please send msg parameter!'

## 
# def index(request,id,nickname):
#     result = 'id: ' + str(id) + "name: " + nickname
#     return HttpResponse(result)

## ３ページ遷移
# def index(request):
#     params = {
#         'title':'hello/index',
#         'msg':'this is sample page',
#         'goto':'next'
#     }
#     return render(request,'hello/index.html',params)
# def next(request):
#     params = {
#         'title':'hello/next',
#         'msg':'this is next page',
#         'goto':'test'
#     }
#     return render(request,'hello/index.html',params)
# def test(request):
#     params = {
#         'title':'hello/test',
#         'msg':'this is test page',
#         'goto':'index'
#     }
#     return render(request,'hello/index.html',params)

## formを作る
# def index(request):
#     params = {
#         'title':'Hello/Index',
#         'msg':'お名前は?'
#     }
#     return render(request, 'hello/index.html', params)

# def form(request):
#     msg = request.POST['msg']
#     params = {
#         'title':'Hello/Form',
#         'msg':'こんにちは' + msg + 'さん。'
#     }
#     return render(request, 'hello/index.html', params)

## forms.pyを使ってformを作る
# def index(request):
#     params = {
#         'title':'Hello',
#         'message':'your data',
#         'form':HelloForm()
#     }
#     if request.method == 'POST':
#         params['message'] = '名前' + request.POST['name'] + \
#             '<br>メール:' + request.POST['mail'] + \
#             '<br>年齢:' + request.POST['age']
#         params['form'] = HelloForm(request.POST)
#     return render(request,'hello/index.html',params)

## HelloViewクラスを作る
# class HelloView(TemplateView):
#     def __init__(self):
#         self.params = {
#             'title':'Hello',
#             'message': 'your data',
#             'form': HelloForm()
#         }
#     def get(self,request):
#         return render(request, 'hello/index.html', self.params)
#     def post(self,request):
#         msg = 'あなたは、<b>' + request.POST['name'] + '(' + request.POST['age'] + ')</b>さんです。<br>メールアドレスは<b>' + request.POST['mail'] + '</b>ですね。'
#         self.params['message'] = msg
#         self.params['form'] = HelloForm(request.POST)
#         return render(request,"hello/index.html",self.params)

## checkboxをクリックするとsuccessと表示する
# class HelloView(TemplateView):
#     def __init__(self):
#         self.params = {
#             'title' : 'hello',
#             'form' : HelloForm(),
#             'result' :  None
#         }
#     def get(self,request):
#         return render(request,"hello/index.html",self.params)
#     def post(self,request):
#         if('check' in request.POST):
#             self.params['result'] = 'Checked!!'
#         else:
#             self.params['result'] = "Not Checked.."
#         self.params['form'] = HelloForm(request.POST)
#         return render(request,"hello/index.html",self.params)

## null も含めたcheck box
# class HelloView(TemplateView):
#     def __init__(self):
#         self.params = {
#             'title':'',
#             'form':HelloForm(),
#             'result':None
#         }
#     def get(self,request):
#         return render(request,"hello/index.html",self.params)
#     def post(self,request):
#         chk = request.POST['check']
#         self.params['result'] = "you checked " + chk + "."
#         self.params['form'] = HelloForm(request.POST)
#         return render(request,"hello/index.html",self.params)

## プルダウンメニューの作成(ラジオボタン、選択リストでも同じでできる)
# class HelloView(TemplateView):
#     def __init__(self):
#         self.params = {
#             'title':'',
#             'form':HelloForm(),
#             'result':None
#         }
#     def get(self,request):
#         return render(request,"hello/index.html",self.params)
#     def post(self,request):
#         ch = request.POST['choice']
#         self.params['result'] = "you checked " + ch + "."
#         self.params['form'] = HelloForm(request.POST)
#         return render(request,"hello/index.html",self.params)

## 複数選択項目リスト
# class HelloView(TemplateView):
#     def __init__(self):
#         self.params = {
#             'title':'',
#             'form':HelloForm(),
#             'result':None
#         }
#     def get(self,request):

django_app/hello/templates/hello/check.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<body class="container">
    <h1 class="display-4 text-primary mb-4">{{title}}</h1>
    <p class="h6 m5-4">{{message|safe}}</p>
    <ol class="list-group">
        {% for item in form %}
        <li class="list-group-item py-2">
            {{ item.name }} ({{item.value}}):{{ item.errors.as_text}}
        </li>
        {% endfor %}
    </ol>
    <form action="{% url 'check' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">名前{{ form.name }}</div>
        <div class="form-group">メール{{ form.mail }}</div>
        <div class="form-group">性別{{ form.gender }}</div>
        <div class="form-group">年齢{{ form.age }}</div>
        <div class="form-group">誕生日{{ form.birthday }}</div>
            <input type="submit" value="click" class="btn btn-primary mt-2">
    </form>
</body>
</html>

django_app/hello/templates/hello/create.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<body class="container">
    <h1 class="display-4 text-primary mb-4">{{title}}</h1>
    <form action="{% url 'create' %}" method="POST">
        {% csrf_token %}
        <table class="table">
        {{ form.as_table }}
            <tr><th><td>
                <input type="submit" value="click" class="btn btn-primary mt-2">
        </td></th></tr>
        </table>
    </form>
</body>
</html>

django_app/hello/templates/hello/delete.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<body class="container">
    <h1 class="display-4 text-primary mb-4">{{title}}</h1>
    <table>
        <tr>
            <th>ID</th>
            <td>{{ obj.id }}</td>
        </tr>
        <tr>
            <th>名前</th>
            <td>{{ obj.name }}</td>
        </tr>
        <tr>
            <th>性別</th>
            <td>
                {% if obj.gender == False %}male{% endif %}
                {% if obj.gender == True %}female{% endif %}
            </td>
        </tr>
        <tr>
            <th>メールアドレス</th>
            <td>{{ obj.mail }}</td>
        </tr>
        <tr>
            <th>誕生日</th>
            <td>{{ obj.birthday }}</td>
        </tr>

        <form action="{% url 'delete' id %}" method="POST">
            {% csrf_token %}
            <tr><th><td>
                <input type="submit" value="click" class="btn btn-primary">
            </td></th></tr>
        </form>
    </table>
</body>
</html>

django_app/hello/templates/hello/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<body class="container">
    <h1 class="display-4 text-primary mb-4">{{title}}</h1>
        <form action="{% url 'edit' id %}" method="POST">
            {% csrf_token %}
            <table class="table">
            {{ form.as_table }}
                <tr><th><td>
                    <input type="submit" value="click" class="btn btn-primary mt-2">
            </td></th></tr>
            </table>
        </form>
</body>
</html>

django_app/hello/templates/hello/find.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<body class="container">
    <h1 class="display-4 text-primary mb-4">{{title}}</h1>
    <p>{{message}}</p>
    <form action="{% url 'find' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="検索">
    </form>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>名前</th>
            <th>メール</th>
        </tr>
        {% for item in data %}
        <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.name }}(){{ item.age }}</td>
            <td>{{ item.mail }}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

django_app/hello/templates/hello/friend_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" crossorigin="anonymous">
    <title>一覧</title>
</head>
<body class="container">
    <h1 class="display-4 text-primary mb-4">一覧</h1>

    <table class="table">
        <tr>
            <th>ID</th>
            <th>名前</th>
            <th>メールアドレス</th>
            <th>性別</th>
            <th>年齢</th>
            <th>誕生日</th>
        </tr>
        <tr>
            <td>{{ object.id }}</td>
            <td>{{ object.name }}</td>
            <td>{{ object.mail }}</td>
            <td>{{ object.gender }}</td>
            <td>{{ object.age }}</td>
            <td>{{ object.birthday }}</td>
        </tr>
    </table>
</body>
</html>

django_app/hello/templates/hello/friend_list.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" crossorigin="anonymous">
    <title>一覧</title>
</head>
<body class="container">
    <h1 class="display-4 text-primary mb-4">一覧</h1>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>名前</th>
        </tr>
        {% for item in object_list %}
        <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.name }}</td>
            <td><a href="/hello/detail/{{item.id}}">詳細</a></td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

django_app/hello/templates/hello/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<body class="container">
    <h1 class="display-4 text-primary mb-4">{{title}}</h1>
    <p class="h6 m5-4">{{message|safe}}</p>
    <!-- <p>{{ msg|safe }}</p> -->
    <!-- <form action="a" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="click">
    </form> -->
    <table class="table">
        <tr>
            <th>ID</th>
            <th>名前</th>
            <th>年齢</th>
            <th>メール</th>
            <th>誕生日</th>
            <th>メッセージ</th>
        </tr>
    {% for item in data %}
        <tr>
            <td>{{item.id}}</td>
            <td>{{item.name}}</td>
            <td>{{item.age}}</td>
            <td>{{item.mail}}</td>
            <td>{{item.birthday}}</td>
            <td>
                <ul>
                    {% for ob in item.message_set.all %}
                        <li>{{ob.title}}</li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
    {% endfor %}
    </table>
    <ul class="pagination justify-content-center">
        {% if data.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{% url 'index' %}">&laquo; 最初</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="{% url 'index' %}{{data.previous_page_number}}">&laquo; 戻る</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link">&laquo; 最初</a>
        </li>
        <li class="page-item">
            <a class="page-link">&laquo; 戻る</a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link">{{data.number}}/{{data.paginator.num_pages}}</a>
        </li>
        {% if data.has_next %}
        <li class="page-item">
            <a class="page-link" href="{% url 'index' %}{{data.next_page_number}}">進む &raquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="{% url 'index' %}{{data.paginator.num_pages}}">最後 &raquo;</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link">進む &raquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link">最後 &raquo;</a>
        </li>
        {% endif %}
    </ul>

    <!-- <table class="table">
        <tr>
            <th>ID</th>
            <th>NAME</th>
            <th>GENDER</th>
            <th>MAIL</th>
            <th>AGE</th>
            <th>BIRTHDAY</th>
        </tr>
        {% for item in data %}
        <tr>
            <td>{{item.id}}</td>
            <td>{{item.name}}</td>
            <td>
                {% if item.gender == False %}male{% endif %}
                {% if item.gender == True %}female{% endif %}
            </td>
            <td>{{item.mail}}</td>
            <td>{{item.age}}</td>
            <td>{{item.birthday}}</td>
        </tr>
        {% endfor %}
    </table> -->
</body>
</html>

django_app/hello/templates/hello/message.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<body class="container">
    <h1 class="display-4 text-primary mb-4">{{title}}</h1>
    <form action="{% url 'message' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="投稿" class="btn btn-primary">
    </form>
    <div class="mt-5"></div>
    <table class="table">
        <tr>
            <th class="py-1">タイトル</th>
            <th class="py-1">名前</th>
            <th class="py-1">時間</th>
        </tr>
    {% for item in data %}
        <tr>
            <td class="py-2">{{item.title}}</td>
            <td class="py-2">{{item.friend.name}}</td>
            <td class="py-2">{{item.pub_date}}</td>
        </tr>
    {% endfor %}
    </table>
    <ul class="pagination justify-content-center">
        {% if data.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{% url 'message' %}">&laquo; 最初</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="{% url 'message' %}{{data.previous_page_number}}">&laquo; 戻る</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link">&laquo; 最初</a>
        </li>
        <li class="page-item">
            <a class="page-link">&laquo; 戻る</a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link">{{data.number}}/{{data.paginator.num_pages}}</a>
        </li>
        {% if data.has_next %}
        <li class="page-item">
            <a class="page-link" href="{% url 'message' %}{{data.next_page_number}}">進む &raquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="{% url 'message' %}{{data.paginator.num_pages}}">最後 &raquo;</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link">進む &raquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link">最後 &raquo;</a>
        </li>
        {% endif %}
    </ul>
</body>
</html>